/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Medicamentos;

import Empleado.Metodos;
import Farmacia.Procesos_Farmacia;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author JL
 */
public class Ventana_Laboratorio extends javax.swing.JFrame 
{
    public static Statement estSQL=null;
    DefaultTableModel modelo=null;
    boolean swCMB=true;
    /**
     * Creates new form Ventana_Laboratorio
     */
    public Ventana_Laboratorio() 
    {
        initComponents();
        insertImage();
        
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/icono.png"));
        setIconImage(icon);
        this.setLocationRelativeTo(null);
        this.setTitle("Laboratorios");
        this.setResizable(false);
        cerrar();
        conexionBD();
        String cabecera[]={};
        String datos[][]={};
        modelo=new DefaultTableModel(datos,cabecera);
        tablaLab.setModel(modelo); 
        swCMB=false;
        genClave();
        cargarComboIdMed();
        genNombreMed();
        swCMB=true;
    }
    public void conexionBD()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        estSQL=sql.conexion("sa", "sa.1","Farmacia", "JOEL-PC\\SQLSERVER2");
    }
    public void cerrar()
    {
        try
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter ()
            {
                public void windowClosing(WindowEvent e)
                {
                    dispose();
                }
            });        
        this.setVisible(true);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelLab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdLab = new javax.swing.JTextField();
        txtNomLab = new javax.swing.JTextField();
        cmbIdMed = new javax.swing.JComboBox();
        txtNomMed = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLab = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        jLabel1.setText("REGISTRO DE LABORATORIOS");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setText("INGRESAR:");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel3.setText("Id. de Laboratorio: ");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel4.setText("Nombre del Laboratorio: ");

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel5.setText("SELECCIONAR MEDICAMENTO: ");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel6.setText("Id. del Medicamento: ");

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel7.setText("Nombre del Medicamento: ");

        txtIdLab.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtIdLab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdLabKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdLabKeyTyped(evt);
            }
        });

        txtNomLab.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N

        cmbIdMed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIdMed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbIdMedItemStateChanged(evt);
            }
        });

        txtNomMed.setEditable(false);
        txtNomMed.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar Registro");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMostrar.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        btnMostrar.setText("Mostrar * Laboratorios");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        tablaLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaLab);

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/stock.png"))); // NOI18N
        btnConsultar.setText("Consultar Medicamentos");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lab.png"))); // NOI18N

        javax.swing.GroupLayout panelLabLayout = new javax.swing.GroupLayout(panelLab);
        panelLab.setLayout(panelLabLayout);
        panelLabLayout.setHorizontalGroup(
            panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabLayout.createSequentialGroup()
                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLabLayout.createSequentialGroup()
                        .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addGroup(panelLabLayout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnMostrar)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnConsultar))
                                    .addGroup(panelLabLayout.createSequentialGroup()
                                        .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(panelLabLayout.createSequentialGroup()
                                                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGap(57, 57, 57)
                                                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtIdLab)
                                                    .addComponent(txtNomLab)
                                                    .addComponent(cmbIdMed, 0, 260, Short.MAX_VALUE)
                                                    .addComponent(txtNomMed)))
                                            .addComponent(jLabel1)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))
                            .addGroup(panelLabLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
        );
        panelLabLayout.setVerticalGroup(
            panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabLayout.createSequentialGroup()
                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLabLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNomLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbIdMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(panelLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnMostrar)
                    .addComponent(btnConsultar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIdMedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbIdMedItemStateChanged
        if (evt.getSource()==cmbIdMed && swCMB) 
        {
            genNombreMed();
        }
    }//GEN-LAST:event_cmbIdMedItemStateChanged

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        limpiarTabla(tablaLab);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        //ResultSet rs=sql.consultarDatos(estSQL, "Select * from farmacia");
        ResultSet rs=sql.consultarDatos(estSQL, "select * from laboratorio");
        sql.procesarRB(rs, modelo);
        
        limpiar();
        editarCabecera();        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Procesos_Farmacia sql=new Procesos_Farmacia();
       String idLab=txtIdLab.getText().trim();
        
        String sentenciaSQL=("insert into laboratorio values ('"+txtIdLab.getText().trim()+"','"+txtNomLab.getText().trim()+"','"+cmbIdMed.getSelectedItem().toString().trim()+"')");
        boolean sw=sql.ingresarDatos(estSQL, sentenciaSQL);
        if(sw==true)
        {
             JOptionPane.showMessageDialog(null,"Registro Guardado con Exito");
        }
        //----------------------------------------------------------------------------
        limpiar(); 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtIdLabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdLabKeyTyped
        
        if(!Character.isDigit(evt.getKeyChar())|| txtIdLab.getText().length()==10)
        evt.consume();
    }//GEN-LAST:event_txtIdLabKeyTyped

    private void txtIdLabKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdLabKeyReleased
        if(evt.getKeyChar()==KeyEvent.VK_B)
        {
             txtIdLab.setBackground(Color.red);
            //////////////////////////////////////
            try
            {
             String sentenciaSQL="select * from laboratorio where id_laboratorio='"+txtIdLab.getText().trim()+"'";
            Metodos obj=new Metodos();
            ResultSet rs=obj.consultaDatos(estSQL, sentenciaSQL);

           
                rs.next();
                txtNomLab.setText(String.valueOf(rs.getObject(2)));
              
               
            }
             catch(Exception E1)
            {
                JOptionPane.showMessageDialog(null,"El Id seleccionado no existe","Error",JOptionPane.ERROR);
                E1.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtIdLabKeyReleased

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        limpiarTabla(tablaLab);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select distinct m.id_medicamento,m.nombre,l.id_laboratorio,l.nombre_lab\n" +
        "from medicamentos m, laboratorio l\n" +
        "where m.id_medicamento=l.id_medicamento");
        sql.procesarRB(rs, modelo);
        limpiar();
        editarCabecera(); 
    }//GEN-LAST:event_btnConsultarActionPerformed

     public void editarCabecera()
    {
        JTableHeader th; 
        th = tablaLab.getTableHeader(); 
        Font fuente = new Font("Consolas", Font.BOLD, 12); 
        th.setFont(fuente); 
    }
    public void genClave()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        String cadeql="select max(id_laboratorio) from laboratorio";
        ResultSet rs=sql.consultarUltimoId(estSQL,cadeql);
        Object valorO;
        try
        {   
            rs.next();
            valorO=rs.getObject(1);    
            if(valorO!=null)
            {
               txtIdLab.setText(Integer.parseInt(valorO.toString().trim())+1+"");
            }else
            {
                txtIdLab.setText(222000+"");
            }
        }catch(Exception e)
        {    
        }
        
    }
    public void limpiarTabla(JTable tabla)
    {
        while(tabla.getRowCount()>0)
        {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    public void limpiar()
    {
        txtIdLab.setBackground(Color.white);
        txtIdLab.setText("");
        txtNomLab.setText("");
        txtNomMed.setText("");
        genClave();
        genNombreMed();
    }
    public void cargarComboIdMed()
    {
        cmbIdMed.removeAllItems();
        swCMB=false;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select id_medicamento from medicamentos order by id_medicamento asc");
        sql.buscarDatosCombo(rs, cmbIdMed);
    }
    public void insertImage()
    {
        ImagePanel Imagen = new ImagePanel();
        panelLab.add(Imagen);
        panelLab.repaint();
    }
    public void genNombreMed()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        
        ResultSet rsP=sql.consultarDatos(estSQL, "select nombre from medicamentos");
        Object valorO;
        try
        {
            rsP.next();
            valorO=rsP.getObject(1);
            if(valorO==null)
            {
                System.out.println("NO HAY VALORES");
            }else
            {
        
                String idMed=cmbIdMed.getSelectedItem().toString().trim();    
                ResultSet rs=sql.consultarDatos(estSQL, "select nombre from medicamentos where id_medicamento='"+idMed+"'");
                try
                {
                    rs.next();
                    txtNomMed.setText(String.valueOf(rs.getObject(1).toString().trim()));
                }catch(java.lang.NullPointerException e)
                {

                }
                catch(Exception e){
                }
            }
        }catch(Exception e)
        {}
    }
    public class ImagePanel extends JPanel 
    {
        public ImagePanel()
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.setSize(670,580);
        }
    @Override
    public void paint(Graphics grafico)
    {
        Dimension height = getSize();
        //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/fondo1.jpg")); 
        //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
        grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
        setOpaque(false);
        super.paintComponent(grafico);
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox cmbIdMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelLab;
    private javax.swing.JTable tablaLab;
    private javax.swing.JTextField txtIdLab;
    private javax.swing.JTextField txtNomLab;
    private javax.swing.JTextField txtNomMed;
    // End of variables declaration//GEN-END:variables
}
